# Generated by Django 4.1.7 on 2023-03-27 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('likes', models.IntegerField(blank=True, default=0, editable=False)),
                ('views', models.IntegerField(blank=True, default=0, editable=False)),
                ('time_create', models.TimeField(auto_now_add=True)),
                ('time_update', models.TimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, null=True)),
                ('pre_karma', models.IntegerField(blank=True, db_index=True, editable=False, null=True)),
                ('karma', models.IntegerField(blank=True, default=0, editable=False)),
                ('contentlen', models.IntegerField(editable=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.language')),
            ],
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.branch')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='links',
            field=models.ManyToManyField(blank=True, through='backend.Relations', to='backend.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='tags',
            field=models.ManyToManyField(blank=True, to='common.tag'),
        ),
        migrations.AddField(
            model_name='branch',
            name='users_learned',
            field=models.ManyToManyField(blank=True, editable=False, related_name='user_learned_Branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='users_liked',
            field=models.ManyToManyField(blank=True, editable=False, related_name='user_liked_Branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='users_wanted',
            field=models.ManyToManyField(blank=True, related_name='user_wanted_to_learn_Branches', to=settings.AUTH_USER_MODEL),
        ),
    ]
