# Generated by Django 4.1.7 on 2023-03-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_relations_parent_karma'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='contentlen',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
