# Generated by Django 4.1.7 on 2023-03-21 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_branch_contentlen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='user_languages', to='backend.language'),
        ),
    ]
